"""Criação das tabelas.

Revision ID: 12f47a8f0a2e
Revises: 
Create Date: 2025-01-17 11:06:14.360454

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12f47a8f0a2e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "individuo",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("telefone", sa.String(), nullable=False),
        sa.Column("nascimento", sa.Date(), nullable=False),
        sa.Column("apelido", sa.String(), nullable=False),
        sa.Column("cpf", sa.String(), nullable=False),
        sa.Column("filter", sa.String(), server_default="", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_individuo_id"), "individuo", ["id"], unique=False)
    op.create_table(
        "usuario",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("senha", sa.String(), nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("papel", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuario_id"), "usuario", ["id"], unique=False)
    op.create_index(op.f("ix_usuario_username"), "usuario", ["username"], unique=True)
    op.execute(
        "insert into usuario (username, nome, papel, senha, ativo) values ('admin@master.com', 'Admin', 'ADMIN', '$2b$12$0oWRX0z0IVEeFXNsJ8e3rOyTv26ck75wlxg9kBK71RVe5MktxLDJS', true)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usuario_username"), table_name="usuario")
    op.drop_index(op.f("ix_usuario_id"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_individuo_id"), table_name="individuo")
    op.drop_table("individuo")
    # ### end Alembic commands ###
