export const HTTP_STATUS_CODE = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDEN: 403,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

export const SERVER_VALIDATION_CODE = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
};

export const ROLES = {
  ADMIN: "ADMIN",
  GESTOR: "GESTOR",
  USER: "USER",
  DIRIGENTE: "DIRIGENTE",
};
